browse:
  credentials: [[ editor, administrator ]]

index:
  credentials: [[ editor, administrator ]]

list:
  credentials: [[ editor, administrator ]]

autocomplete:
  is_secure: false

all:
  is_secure: true
